name: testtest
run-name: Release of ${{ github.ref_name }}

on:
  push:
    tags:
    admin-ui-1.0.0-rc.1
      - 'admin-ui-[1-9]+.[0-9]+.[0-9]+*'
      - 'kc-themes-[1-9]+.[0-9]+.[0-9]+.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Checkout
        uses: actions/checkout@v3
